// GENERATED by tool/build_tokens.mjs from design-tokens/tokens.json — do not edit by hand.
// Regenerate: `node tool/build_tokens.mjs` (or `melos run tokens`), then `dart format`.

// AMDS v1.0.0 · primitives + scales + typography + motion.
// Semantic theme wiring lives in theme_ext.dart / theme.dart.

import 'package:flutter/widgets.dart';

/// Raw color ramps. Prefer the semantic set on `context.amds.colors`.
abstract final class AmdsPalette {
  // brand / green
  static const green50 = Color(0xFFF0FDF4);
  static const green100 = Color(0xFFDCFCE7);
  static const green200 = Color(0xFFBBF7D0);
  static const green300 = Color(0xFF86EFAC);
  static const green400 = Color(0xFF4ADE80);
  static const green500 = Color(0xFF22C55E);
  static const green600 = Color(0xFF16A34A);
  static const green700 = Color(0xFF15803D);
  static const green800 = Color(0xFF166534);
  static const green900 = Color(0xFF14532D);
  static const green950 = Color(0xFF052E16);

  // neutral / slate
  static const neutral0 = Color(0xFFFFFFFF);
  static const neutral50 = Color(0xFFF8FAFC);
  static const neutral100 = Color(0xFFF1F5F9);
  static const neutral200 = Color(0xFFE2E8F0);
  static const neutral300 = Color(0xFFCBD5E1);
  static const neutral400 = Color(0xFF94A3B8);
  static const neutral500 = Color(0xFF64748B);
  static const neutral600 = Color(0xFF475569);
  static const neutral700 = Color(0xFF334155);
  static const neutral800 = Color(0xFF1E293B);
  static const neutral900 = Color(0xFF0F172A);
  static const neutral950 = Color(0xFF020617);
  static const neutral1000 = Color(0xFF000000);

  // status hues
  static const amber50 = Color(0xFFFFFBEB);
  static const amber100 = Color(0xFFFEF3C7);
  static const amber400 = Color(0xFFFBBF24);
  static const amber500 = Color(0xFFF59E0B);
  static const amber600 = Color(0xFFD97706);
  static const amber700 = Color(0xFFB45309);

  static const red50 = Color(0xFFFEF2F2);
  static const red100 = Color(0xFFFEE2E2);
  static const red400 = Color(0xFFF87171);
  static const red500 = Color(0xFFEF4444);
  static const red600 = Color(0xFFDC2626);
  static const red700 = Color(0xFFB91C1C);

  static const sky50 = Color(0xFFF0F9FF);
  static const sky100 = Color(0xFFE0F2FE);
  static const sky400 = Color(0xFF38BDF8);
  static const sky500 = Color(0xFF0EA5E9);
  static const sky600 = Color(0xFF0284C7);
  static const sky700 = Color(0xFF0369A1);
}

/// Spacing scale (4pt base). Values are logical pixels.
abstract final class AmdsSpacing {
  static const s0 = 0.0;
  static const s1 = 4.0;
  static const s2 = 8.0;
  static const s3 = 12.0;
  static const s4 = 16.0;
  static const s5 = 20.0;
  static const s6 = 24.0;
  static const s8 = 32.0;
  static const s10 = 40.0;
  static const s12 = 48.0;
  static const s16 = 64.0;

  static const none = s0;
  static const xxs = s1;
  static const xs = s2;
  static const sm = s3;
  static const md = s4; // default
  static const lg = s6;
  static const xl = s8;
  static const xxl = s12;
}

/// Corner radius scale.
abstract final class AmdsRadius {
  static const xs = 4.0;
  static const sm = 8.0;
  static const md = 12.0;
  static const lg = 16.0;
  static const xl = 24.0;
  static const xxl = 32.0;
  static const full = 9999.0;

  static const BorderRadius brXs = BorderRadius.all(Radius.circular(xs));
  static const BorderRadius brSm = BorderRadius.all(Radius.circular(sm));
  static const BorderRadius brMd = BorderRadius.all(Radius.circular(md));
  static const BorderRadius brLg = BorderRadius.all(Radius.circular(lg));
  static const BorderRadius brXl = BorderRadius.all(Radius.circular(xl));
  static const BorderRadius brFull = BorderRadius.all(Radius.circular(full));
}

abstract final class AmdsBorderWidth {
  static const hairline = 1.0;
  static const thin = 1.5;
  static const thick = 2.0;
  static const focus = 2.0;
}

/// Component sizing.
abstract final class AmdsSize {
  static const touchTargetMin = 44.0;
  static const touchTargetComfortable = 48.0;
  static const iconXs = 16.0;
  static const iconSm = 20.0;
  static const iconMd = 24.0;
  static const iconLg = 32.0;
  static const iconXl = 40.0;
  static const avatarXs = 24.0;
  static const avatarSm = 32.0;
  static const avatarMd = 40.0;
  static const avatarLg = 56.0;
  static const avatarXl = 80.0;
  static const buttonHeightSm = 36.0;
  static const buttonHeightMd = 44.0;
  static const buttonHeightLg = 52.0;
  static const fieldHeight = 48.0;
  static const appBarHeight = 56.0;
  static const bottomNavHeight = 64.0;
  static const fabSize = 56.0;
  static const fabSizeSmall = 40.0;

  // aliases
  static const touchTarget = touchTargetMin;
  static const fab = fabSize;
}

/// Responsive breakpoints (min width, logical px).
abstract final class AmdsBreakpoints {
  static const phoneSmall = 320.0;
  static const phoneMedium = 375.0;
  static const phoneLarge = 430.0;
  static const tabletPortrait = 600.0;
  static const tabletLandscape = 905.0;
  static const desktop = 1240.0;
}

/// Motion tokens — durations 100..400ms and the four named easings.
abstract final class AmdsMotion {
  static const instant = Duration(milliseconds: 100);
  static const fast = Duration(milliseconds: 150);
  static const base = Duration(milliseconds: 200);
  static const moderate = Duration(milliseconds: 250);
  static const slow = Duration(milliseconds: 300);
  static const slower = Duration(milliseconds: 400);

  static const Curve standard = Cubic(0.2, 0.0, 0.0, 1.0);
  static const Curve decelerate = Cubic(0.0, 0.0, 0.0, 1.0);
  static const Curve accelerate = Cubic(0.3, 0.0, 1.0, 1.0);
  static const Curve emphasized = Cubic(0.2, 0.0, 0.0, 1.0);
  static const Curve spring = Cubic(0.34, 1.56, 0.64, 1.0);
}

/// Elevation as `BoxShadow` sets. Level 0 is flat (use a 1px border instead).
abstract final class AmdsElevation {
  static const _lightShadow = Color(0xFF0F172A);
  static const _darkShadow = Color(0xFF000000);

  static List<BoxShadow> level(int level,
      {Brightness brightness = Brightness.light}) {
    final dark = brightness == Brightness.dark;
    final c = dark ? _darkShadow : _lightShadow;
    switch (level) {
      case 1:
        return [
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.40 : 0.06),
              blurRadius: 2,
              offset: const Offset(0, 1))
        ];
      case 2:
        return [
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.44 : 0.08),
              blurRadius: 4,
              spreadRadius: -1,
              offset: const Offset(0, 2)),
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.32 : 0.04),
              blurRadius: 2,
              offset: const Offset(0, 1)),
        ];
      case 3:
        return [
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.48 : 0.10),
              blurRadius: 8,
              spreadRadius: -2,
              offset: const Offset(0, 4)),
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.36 : 0.05),
              blurRadius: 4,
              spreadRadius: -1,
              offset: const Offset(0, 2)),
        ];
      case 4:
        return [
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.52 : 0.12),
              blurRadius: 20,
              spreadRadius: -4,
              offset: const Offset(0, 12)),
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.40 : 0.06),
              blurRadius: 8,
              spreadRadius: -2,
              offset: const Offset(0, 4)),
        ];
      case 5:
        return [
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.60 : 0.16),
              blurRadius: 40,
              spreadRadius: -8,
              offset: const Offset(0, 24)),
          BoxShadow(
              color: c.withValues(alpha: dark ? 0.44 : 0.08),
              blurRadius: 16,
              spreadRadius: -4,
              offset: const Offset(0, 8)),
        ];
      default:
        return const [];
    }
  }
}

/// The AMDS type scale (Inter). See `amdsTextTheme` in theme.dart for the
/// Material 3 `TextTheme` mapping used by built-in widgets.
abstract final class AmdsTextStyles {
  static const String fontFamily = 'Inter';

  static const displayLarge = TextStyle(
      fontFamily: fontFamily,
      fontSize: 36.0,
      height: 44.0 / 36.0,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.72);
  static const displayMedium = TextStyle(
      fontFamily: fontFamily,
      fontSize: 32.0,
      height: 40.0 / 32.0,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.64);
  static const displaySmall = TextStyle(
      fontFamily: fontFamily,
      fontSize: 28.0,
      height: 36.0 / 28.0,
      fontWeight: FontWeight.w700,
      letterSpacing: -0.28);
  static const headingLarge = TextStyle(
      fontFamily: fontFamily,
      fontSize: 24.0,
      height: 32.0 / 24.0,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.24);
  static const headingMedium = TextStyle(
      fontFamily: fontFamily,
      fontSize: 20.0,
      height: 28.0 / 20.0,
      fontWeight: FontWeight.w600,
      letterSpacing: -0.2);
  static const headingSmall = TextStyle(
      fontFamily: fontFamily,
      fontSize: 18.0,
      height: 26.0 / 18.0,
      fontWeight: FontWeight.w600);
  static const titleLarge = TextStyle(
      fontFamily: fontFamily,
      fontSize: 16.0,
      height: 24.0 / 16.0,
      fontWeight: FontWeight.w600);
  static const titleMedium = TextStyle(
      fontFamily: fontFamily,
      fontSize: 14.0,
      height: 20.0 / 14.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.07);
  static const bodyLarge = TextStyle(
      fontFamily: fontFamily,
      fontSize: 16.0,
      height: 24.0 / 16.0,
      fontWeight: FontWeight.w400);
  static const bodyMedium = TextStyle(
      fontFamily: fontFamily,
      fontSize: 14.0,
      height: 20.0 / 14.0,
      fontWeight: FontWeight.w400);
  static const bodySmall = TextStyle(
      fontFamily: fontFamily,
      fontSize: 13.0,
      height: 18.0 / 13.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.065);
  static const label = TextStyle(
      fontFamily: fontFamily,
      fontSize: 14.0,
      height: 16.0 / 14.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.14);
  static const labelSmall = TextStyle(
      fontFamily: fontFamily,
      fontSize: 12.0,
      height: 16.0 / 12.0,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.24);
  static const caption = TextStyle(
      fontFamily: fontFamily,
      fontSize: 12.0,
      height: 16.0 / 12.0,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.12);
  static const overline = TextStyle(
      fontFamily: fontFamily,
      fontSize: 11.0,
      height: 16.0 / 11.0,
      fontWeight: FontWeight.w600,
      letterSpacing: 0.88);
}

/// Opacity tokens for interaction overlays.
abstract final class AmdsOpacity {
  static const disabled = 0.38;
  static const hover = 0.08;
  static const pressed = 0.12;
  static const focus = 0.12;
  static const dragged = 0.16;
  static const scrim = 0.48;
}
