#!/usr/bin/env node
// Generate packages/amds_tokens/lib/src/tokens.dart from design-tokens/tokens.json.
//   node tool/build_tokens.mjs        (or: melos run tokens)
//
// Emits: AmdsPalette (primitive ramps) + AmdsSpacing/Radius/BorderWidth/Size/
// Breakpoints (scales) + AmdsMotion + AmdsElevation + AmdsTextStyles + AmdsOpacity.
// The semantic layer (AmdsColors) and ThemeData wiring stay hand-maintained in
// theme_ext.dart / theme.dart — they reference the names emitted here.
import { readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]):/, '$1:');
const T = JSON.parse(readFileSync(`${ROOT}/design-tokens/tokens.json`, 'utf8'));
const OUT = `${ROOT}/packages/amds_tokens/lib/src/tokens.dart`;

const val = (node) => (node && typeof node === 'object' && '$value' in node ? node.$value : node);

// #RRGGBB or #RRGGBBAA -> Dart Color(0xAARRGGBB)
function color(hex) {
  let h = String(hex).replace('#', '').toUpperCase();
  if (h.length === 6) h = 'FF' + h;
  else if (h.length === 8) h = h.slice(6) + h.slice(0, 6); // RGBA -> ARGB
  return `Color(0x${h})`;
}
const camel = (r, k) => `${r}${k}`;
// always emit a Dart double literal (named int consts don't coerce to double params)
const d = (n) => (Number.isInteger(Number(n)) ? `${Number(n)}.0` : `${Number(n)}`);

function ramp(name, obj) {
  const lines = Object.entries(obj)
    .filter(([k]) => /^\d+$/.test(k) && Number(k) <= 950)
    .map(([k, v]) => `  static const ${camel(name, k)} = ${color(val(v))};`);
  return lines.join('\n');
}

const c = T.color;
const palette = [
  '  // brand / green',
  ramp('green', c.brand.green),
  '',
  '  // neutral / slate',
  ramp('neutral', c.neutral),
  `  static const neutral1000 = ${color(val(c.neutral['1000']) ?? '#000000')};`,
  '',
  '  // status hues',
  ramp('amber', c.amber),
  '',
  ramp('red', c.red),
  '',
  ramp('sky', c.sky),
].join('\n');

const spaceMap = { 0: 's0', 1: 's1', 2: 's2', 3: 's3', 4: 's4', 5: 's5', 6: 's6', 8: 's8', 10: 's10', 12: 's12', 16: 's16' };
const spacing = Object.entries(T.space)
  .filter(([k]) => spaceMap[k])
  .map(([k, v]) => `  static const ${spaceMap[k]} = ${d(parseFloat(val(v)))};`)
  .join('\n');

const radius = Object.entries(T.radius)
  .filter(([k]) => k !== '$type' && k !== 'full')
  .map(([k, v]) => `  static const ${k.replace('2xl', 'xxl')} = ${d(parseFloat(val(v)))};`)
  .join('\n');

const size = Object.entries(T.size)
  .filter(([k]) => k !== '$type')
  .map(([k, v]) => `  static const ${k} = ${d(parseFloat(val(v)))};`)
  .join('\n');

const bp = Object.entries(T.breakpoint)
  .filter(([k]) => k !== '$type')
  .map(([k, v]) => `  static const ${k} = ${d(parseFloat(val(v)))};`)
  .join('\n');

const dur = Object.entries(T.motion.duration)
  .filter(([k]) => k !== '$type')
  .map(([k, v]) => `  static const ${k} = Duration(milliseconds: ${parseInt(val(v))});`)
  .join('\n');

const ease = Object.entries(T.motion.easing)
  .filter(([k]) => k !== '$type')
  .map(([k, v]) => {
    const [x1, y1, x2, y2] = val(v).map((n) => d(n));
    return `  static const Curve ${k} = Cubic(${x1}, ${y1}, ${x2}, ${y2});`;
  })
  .join('\n');

// resolve a "{font.weight.bold}" reference (or a bare number) to 400..700
function weight(ref) {
  const m = String(ref).match(/\{font\.weight\.(\w+)\}/);
  const n = m ? Number(val(T.font.weight[m[1]])) : Number(ref);
  return Number.isFinite(n) ? n : 400;
}
const type = Object.entries(T.typography)
  .filter(([k]) => k !== '$type')
  .map(([k, v]) => {
    const t = val(v);
    const fs = parseFloat(t.fontSize);
    const lh = parseFloat(t.lineHeight);
    const wt = weight(t.fontWeight);
    const lsEm = parseFloat(String(t.letterSpacing).replace('em', '')) || 0;
    const ls = +(lsEm * fs).toFixed(3);
    const lsPart = ls === 0 ? '' : `, letterSpacing: ${ls}`;
    return `  static const ${k} = TextStyle(fontFamily: fontFamily, fontSize: ${d(fs)}, height: ${d(lh)} / ${d(fs)}, fontWeight: FontWeight.w${wt}${lsPart});`;
  })
  .join('\n');

const out = `// GENERATED by tool/build_tokens.mjs from design-tokens/tokens.json — do not edit by hand.
// Regenerate: \`node tool/build_tokens.mjs\` (or \`melos run tokens\`).
//
// AMDS v${T.meta.version} · primitives + scales + typography + motion.
// Semantic theme wiring lives in theme_ext.dart / theme.dart.

import 'package:flutter/widgets.dart';

/// Raw color ramps. Prefer the semantic set on \`context.amds.colors\`.
abstract final class AmdsPalette {
${palette}
}

/// Spacing scale (4pt base). Values are logical pixels.
abstract final class AmdsSpacing {
${spacing}

  static const none = s0;
  static const xxs = s1;
  static const xs = s2;
  static const sm = s3;
  static const md = s4; // default
  static const lg = s6;
  static const xl = s8;
  static const xxl = s12;
}

/// Corner radius scale.
abstract final class AmdsRadius {
${radius}
  static const full = 9999.0;

  static const BorderRadius brXs = BorderRadius.all(Radius.circular(xs));
  static const BorderRadius brSm = BorderRadius.all(Radius.circular(sm));
  static const BorderRadius brMd = BorderRadius.all(Radius.circular(md));
  static const BorderRadius brLg = BorderRadius.all(Radius.circular(lg));
  static const BorderRadius brXl = BorderRadius.all(Radius.circular(xl));
  static const BorderRadius brFull = BorderRadius.all(Radius.circular(full));
}

abstract final class AmdsBorderWidth {
  static const hairline = 1.0;
  static const thin = 1.5;
  static const thick = 2.0;
  static const focus = 2.0;
}

/// Component sizing.
abstract final class AmdsSize {
${size}

  // aliases
  static const touchTarget = touchTargetMin;
  static const fab = fabSize;
}

/// Responsive breakpoints (min width, logical px).
abstract final class AmdsBreakpoints {
${bp}
}

/// Motion tokens — durations 100..400ms and the four named easings.
abstract final class AmdsMotion {
${dur}

${ease}
}

/// Elevation as \`BoxShadow\` sets. Level 0 is flat (use a 1px border instead).
abstract final class AmdsElevation {
  static const _lightShadow = Color(0xFF0F172A);
  static const _darkShadow = Color(0xFF000000);

  static List<BoxShadow> level(int level, {Brightness brightness = Brightness.light}) {
    final dark = brightness == Brightness.dark;
    final c = dark ? _darkShadow : _lightShadow;
    switch (level) {
      case 1:
        return [BoxShadow(color: c.withValues(alpha: dark ? 0.40 : 0.06), blurRadius: 2, offset: const Offset(0, 1))];
      case 2:
        return [
          BoxShadow(color: c.withValues(alpha: dark ? 0.44 : 0.08), blurRadius: 4, spreadRadius: -1, offset: const Offset(0, 2)),
          BoxShadow(color: c.withValues(alpha: dark ? 0.32 : 0.04), blurRadius: 2, offset: const Offset(0, 1)),
        ];
      case 3:
        return [
          BoxShadow(color: c.withValues(alpha: dark ? 0.48 : 0.10), blurRadius: 8, spreadRadius: -2, offset: const Offset(0, 4)),
          BoxShadow(color: c.withValues(alpha: dark ? 0.36 : 0.05), blurRadius: 4, spreadRadius: -1, offset: const Offset(0, 2)),
        ];
      case 4:
        return [
          BoxShadow(color: c.withValues(alpha: dark ? 0.52 : 0.12), blurRadius: 20, spreadRadius: -4, offset: const Offset(0, 12)),
          BoxShadow(color: c.withValues(alpha: dark ? 0.40 : 0.06), blurRadius: 8, spreadRadius: -2, offset: const Offset(0, 4)),
        ];
      case 5:
        return [
          BoxShadow(color: c.withValues(alpha: dark ? 0.60 : 0.16), blurRadius: 40, spreadRadius: -8, offset: const Offset(0, 24)),
          BoxShadow(color: c.withValues(alpha: dark ? 0.44 : 0.08), blurRadius: 16, spreadRadius: -4, offset: const Offset(0, 8)),
        ];
      default:
        return const [];
    }
  }
}

/// The AMDS type scale (Inter). See \`amdsTextTheme\` in theme.dart for the
/// Material 3 \`TextTheme\` mapping used by built-in widgets.
abstract final class AmdsTextStyles {
  static const String fontFamily = 'Inter';

${type}
}

/// Opacity tokens for interaction overlays.
abstract final class AmdsOpacity {
  static const disabled = ${val(T.opacity.disabled)};
  static const hover = ${val(T.opacity.hover)};
  static const pressed = ${val(T.opacity.pressed)};
  static const focus = ${val(T.opacity.focus)};
  static const dragged = ${val(T.opacity.dragged)};
  static const scrim = ${val(T.opacity.scrim)};
}
`;

writeFileSync(OUT, out);

// Normalize with the Dart formatter so the committed file matches `dart format`
// output exactly — otherwise CI's token-freshness diff trips on whitespace.
const fmt = spawnSync(`dart format "${OUT}"`, { stdio: 'inherit', shell: true });
if (fmt.status !== 0) {
  console.warn('warning: `dart format` unavailable — committed tokens.dart may need manual formatting');
}

console.log(`wrote ${OUT.replace(ROOT, '.')}  (${out.split('\n').length} lines)`);
console.log('note: theme_ext.dart (AmdsColors) + theme.dart (ThemeData) are hand-maintained.');
